### ISSUE TITLE
Mousewheel zooms not scrolls

### ISSUE THREAD

**Issue by kuiperzone** [toolstack/Folio#121]
Strange intermittent problem.

Initially, the mouse wheel scrolls. But then, for unknown reason, switches to zooming the text. The only way to stop it is to restart folio.

On Deb 12, Gnome, wayland.

**Comment by toolstack** [comment]
I have seen this myself but have never been able to get it to replicate consistently to track down what's going on.

If anyone can replicate it consistently that would be helpful.

**Comment by machitgarha** [comment]
@toolstack, I found it. Focus on the editing view and press control. This practically means when you press any shortcuts, like saving (ctrl+s) or copying and pasting, the view gets corrupted.

**Comment by kuiperzone** [comment]
By way of constructive feedback...

I've gone back to using Paper. Partly because of this bug, and partly because of the link feature.

To be honest, I don't even want markdown. I want simple text. Some of the stuff I store IS markdown and I want to see the raw text. Editing styles can also be an exercise that serves no real purpose. A way of disabling markdown would be good.

Hope to use Folio in the future. Best wishes

**Comment by toolstack** [comment]
@machitgarha Thanks, should be relatively straight forward to track down, must be some kind of error with the ctrl key detection.

@kuiperzone you could always just use Folio with text mode instead of markdown mode, just name your files with a txt extension.

**Comment by machitgarha** [comment]
@kuiperzone, I have Paper installed and it has this particular zooming bug. I suppose you're using an old version that is free of this bug, am I right?

**Comment by kuiperzone** [comment]
> @kuiperzone, I have Paper installed and it has this particular zooming bug. I suppose you're using an old version that is free of this bug, am I right?

Let's have a look -- 22.11

**Comment by machitgarha** [comment]
> Let's have a look -- 22.11

I also have this version. You don't have the bug?

**Comment by machitgarha** [comment]
The bug seems to only happen when keyboard layout switch keybinding is set to both controls is set. Tested with both KDE and Sway. Changing it to something else (e.g. ctrl+shift) fixes the issue. @kuiperzone, is this the case?

Disabling the control capturing [here](https://github.com/toolstack/Folio/blob/main/src/ui/edit_view/edit_view.vala#L173) also works around the issue.

**Comment by machitgarha** [comment]
@toolstack, is it possible to add an option for disabling the ctrl+mousewheel zoom feature?

**Comment by toolstack** [comment]
@machitgarha I don't seem to be able to reproduce this on my system, so let me double check I understand the steps to reproduce it:
1. Load Folio
1. Select a note
1. click inside the edit/view pane
1. make a change
1. use a ctl based shortcut (like ctl-s to save the note)
1. then use the scroll wheel, which should now zoom instead of scroll the note

Did I miss anything?

**Comment by toolstack** [comment]
> @toolstack, is it possible to add an option for disabling the ctrl+mousewheel zoom feature?

Maybe?  I think it's part of the sourceview widget (more likely part of the textview widget the srouceview is based on), so it would be deep in the gnome library somewhere.

**Comment by toolstack** [comment]
@machitgarha never mind on the steps, I've got it to reproduce now.

**Comment by machitgarha** [comment]
> > @toolstack, is it possible to add an option for disabling the ctrl+mousewheel zoom feature?
> 
> Maybe? I think it's part of the sourceview widget (more likely part of the textview widget the srouceview is based on), so it would be deep in the gnome library somewhere.

It's easier than that, as I mentioned earlier. You just need to prevent capturing key press and release of ctrl [here in the code](https://github.com/toolstack/Folio/blob/main/src/ui/edit_view/edit_view.vala#L173).

But now that I think of it, it's only a temporary workaround. Future users would still need to figure out what the problem is (if they don't uninstall the app immediately because of the bug). So while having an opt-out setting works, the fix should be permanent.

Yesterday I thought as though the problem is not with the app, but with one on the system components (e.g. xkb). But I just tested [GNOME Text Editor](https://gitlab.gnome.org/GNOME/gnome-text-editor), and it doesn't have this particular bug. Now I suppose we shouldn't capture the control key like that (maybe special keys should be handled in another way).

P.S.: I changed my keyboard layout switch keybinding now as a workaround.

**Comment by toolstack** [comment]
I track down what's happening, but I'm not sure of the fix yet.

Basically, the code to detect the ctrl key state change is tied to the editor window, if a ctrl combo is pressed and changes the focus to another window, the editor window no longer receives notifications of key state changes.  This means that when you release the ctrl key without the focus being on the editor window, the editor window never realizes the ctrl key has been released.

Going back to the editor and simply tapping the ctrl key clears the state again.

The obvious "fix" is to simply check the ctrl key state instead of monitoring the up/down changes, but I'm not seeing a way to do that in GTK at the moment.  The other fix would be to clear the ctrl state on losing the focus, but I'm not finding a solution (that works) so far the capture the lose of focus event yet.
