### ISSUE TITLE
Selected text is not highlighted

### ISSUE THREAD

**Issue by frandavid100** [toolstack/Folio#140]
When you select text on Folio it's not highlighted, so there's no visual way to know what text is selected.

**Comment by toolstack** [comment]
Works for me, can you provide some details on your system setup?

**Comment by frandavid100** [comment]
I have noticed it only happens when you double-click an .md file to open it with Folio. When you use Folio normally, it does work.

Can you test that?

**Comment by toolstack** [comment]
Works both ways for me.

**Comment by toolstack** [comment]
Closing for now as no additional detail has been provided.

**Comment by GabePoel** [comment]
I'm having this issue as well. Without looking at the code base at all, I'm guessing it's because there's no current notebook selected and therefore no highlight color. If I have a main Folio window open with a notebook open, then I can select text in a file I double-click to open just fine.

![Screenshot From 2024-11-09 12-04-17](https://github.com/user-attachments/assets/9b1b9731-3ae3-4fc9-9dc6-126f4d3c2c97)

And the color of the selected text in the file that's not in the notebook matches the color of the notebook in the other window.

![Screenshot From 2024-11-09 12-05-16](https://github.com/user-attachments/assets/372a1093-0511-45e7-b385-3de329b3ec75)

However, if there's no notebook open, then the selected text has no color. (All the text is selected in the following picture, but there's no color to denote that.)

![Screenshot From 2024-11-09 12-03-09](https://github.com/user-attachments/assets/9afbcdbb-5e0a-431e-b68f-5d29bc55eae9)

Maybe having some default color would fix this?
