### ISSUE TITLE
Text selection not visible

### ISSUE THREAD

**Issue by sebastianbota** [toolstack/Folio#175]
After installing Folio, .md files are automaticaly opened with Folio ( this is great )
When you open a .md file and try to select text using mouse for example, the selection is not visible. There is no visual indicator that the text is selected whatsoever. You can use CRTL+C to copy the text , but the user does not see what is actualy selected.

This does not happen if you open the note right from Folio App

**Comment by toolstack** [comment]
I can't reproduce this, can you provide some details on which version (flatpak/snap) you're using and what OS?

**Comment by sebastianbota** [comment]
> I can't reproduce this, can you provide some details on which version (flatpak/snap) you're using and what OS?

The described behaviour occurs in the Flatpack application ( openSUSE - Gnome )

**Comment by toolstack** [comment]
Ok, I've been able to reproduce this on openSUSE and another distro, but it seems to be distro dependent, as the same package works fine on Fedora.

I'll leave this open and see if I can track down what's going on, but there might not be anything for me to do.

**Comment by GabePoel** [comment]
I'm having this issue as well (on Fedora Silverblue). Without looking at the code base at all, I'm guessing it's because there's no current notebook selected and therefore no highlight color. If I have a main Folio window open with a notebook open, then I can select text in a file I double-click to open just fine.

![Screenshot From 2024-11-09 12-04-17](https://github.com/user-attachments/assets/9b1b9731-3ae3-4fc9-9dc6-126f4d3c2c97)

And the color of the selected text in the file that's not in the notebook matches the color of the notebook in the other window.

![Screenshot From 2024-11-09 12-05-16](https://github.com/user-attachments/assets/372a1093-0511-45e7-b385-3de329b3ec75)

However, if there's no notebook open, then the selected text has no color. (All the text is selected in the following picture, but there's no color to denote that.)

![Screenshot From 2024-11-09 12-03-09](https://github.com/user-attachments/assets/9afbcdbb-5e0a-431e-b68f-5d29bc55eae9)

Maybe having some default color would fix this?

**Comment by toolstack** [comment]
That does seem to be the issue, thanks for the input.
