### ISSUE TITLE
Change position of the main menu

### ISSUE THREAD

**Issue by vanillajonathan** [toolstack/Folio#222]
The main menu `open-menu-symbolic` is currently on the left side of the `AdwNavigationPage`. In other applications such as GNOME Builder, Nautilus, Settings, Tweaks and Endeavour the main menu is on the right side of the side bar (where the search button is right now).

So I think you should switch position of the search button and the main menu so that the search button is on the left side and the main menu is on the right side.

**Comment by toolstack** [comment]
We're a three pane app, so the main menu is on the right side of the left most pane, the search is similarly on the right most of the center pane, and the overflow menu is on the rightmost of the third pane.

This is the same as Nautilus, Newsfeed and other gnome apps.

**Comment by vanillajonathan** [comment]
Hmm...

![image](https://github.com/user-attachments/assets/8c554bbe-6d64-4cf0-b4e6-ba8f0a117ecf)

**Comment by toolstack** [comment]
Go to Preferences->Layout- and enable 3-Pane Layout and you'll get a better view of what's going on.

But in general:
![3panes](https://github.com/user-attachments/assets/95867a32-6cb3-422b-a7d7-a2e463b4105d)

So the left most pane is collapsed, but still a pane, so the menu is actually at the right of the pane, but that's the same as the left when collapsed ;)

Expanding the first pane reveals the truth:

![Screenshot From 2024-11-14 17-32-46](https://github.com/user-attachments/assets/6915e056-f28f-4d6d-b215-20f0f79314ce)

On the other hand, I have no idea why your main menu is the vertical three dots instead of the hamburger icon 🤷

**Comment by vanillajonathan** [comment]
I see, now it makes a bit more sense even though it was confusing at first.

My icons are different because I installed a icon set called Gruvbox.
https://github.com/TheGreatMcPain/gruvbox-material-gtk
