### ISSUE TITLE
Motivation of the fork

### ISSUE THREAD

**Issue by lightonflux** [toolstack/Folio#7]
Hello, I just saw the Flathub release and checked if Paper was still in development. And it is. So I am wondering what the motivation for forking was. What advantages does Folio hope to provide to its users? Usually, forks provide this information in their readme (or similar) to attract user and contributors. 

Thank you.

**Comment by toolstack** [comment]
Unfortunately the developer has gone radio silent again after applying a few of the simplest PR's and not doing a release, hence the fork.

You'll notice that all of the outstanding PR's on Paper are from me, and with no communications on any of them, I decided to proceed with my fork.

The primary focus of my fork is getting everything up to date and supported for the long term.

As for advantages, Folio is up to date, using the GNOME 45 runtime so no errors during updates about end of life runtimes.  In addition the following changes have been done:
 - Fixed unable to save changes editing of notebook details without changing notebook name.
 - New icon.
 - Handle escaped characters inside code span/blocks.
 - Fixed dark mode in flatpak.
 - Rework the format bar so that it works more like a standard toolbar.  Toggle formats on and off, format around current word if none selected, place the text/url parts into the right area when creating a new link, don't split current line when inserting a new HR, return focus to the editor after clicking a format button, and return the cursor to the right position.
 - Update deprecated font selector dialogs.
 - Fixed note title not being updated when renamed.
 - Renaming a not active note no longer makes it active.
 - Make sure to update the title bar when renaming a note.
 - Add translator credits.
 - Fixed GNOME search results.
 - Fixed new notes names not being translated.
 - Remove dialog highlights between boxes.
 - Fixed crashes when the last line of a file doesn't contain a terminating LF.
 - Warn about duplicate notebook names when creating new notebooks.
 - Cleanup complier warnings during build.
 - None
 - Fix incorrect display of switches in the preferences window
 - Place cursor between formatting characters when using formatting shortcuts (thanks u1f98e@gitlab)
 - Updated to libadwaita 1.4.2
 - Upgrade to Gnome runtime version 45 (thanks @tpikonen)

The next release will have additional functionality as well:
- highlighting bare links (aka links not formatted in markdown will look like links)
- links will be ctrl-clickable to open
  
Future plans include:
- markdown parser rewrite
- updates to move deprecated adwiata widgets to supported ones
